### ISSUE TITLE
Problemer med at navkontor er null

### ISSUE THREAD

**Issue by MikAoJk** [navikt/pale#5]
Har nok sammenheng med problemstillingen rundt geografiskTilknytning, meldingen går til backout men burde gått til manuell behandling, med tomt tknummer

**Comment by MikAoJk** [comment]
stackstrace`java.lang.IllegalStateException: runBlocking { navKontorDeferred.await() } must not be null
	at no.nav.pale.PaleApplicationKt.validateMessage(PaleApplication.kt:410)
	at no.nav.pale.PaleApplicationKt$listen$1$1.onMessage(PaleApplication.kt:268)
	at com.ibm.mq.jms.MQMessageConsumer$FacadeMessageListener.onMessage(MQMessageConsumer.java:324)
	at com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl$JmsProviderMessageListener.onMessage(JmsMessageConsumerImpl.java:1214)
	at com.ibm.msg.client.wmq.internal.WMQAsyncConsumerShadow.honourNoLocal(WMQAsyncConsumerShadow.java:687)
	at com.ibm.msg.client.wmq.internal.WMQAsyncConsumerShadow.consumer(WMQAsyncConsumerShadow.java:514)
	at com.ibm.mq.jmqi.remote.impl.RemoteProxyQueue.driveConsumer(RemoteProxyQueue.java:4416)
	at com.ibm.mq.jmqi.remote.impl.RemoteProxyQueue.deliverMsgs(RemoteProxyQueue.java:5015)
	at com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.deliverMsgsReconnectable(RemoteDispatchThread.java:536)
	at com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.deliverMsgs(RemoteDispatchThread.java:509)
	at com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.run(RemoteDispatchThread.java:277)
	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)`

PATIENT_EMIGRATED er outcome type

**Comment by MikAoJk** [comment]
Ble fikset i commiten: e07410ccfca0c776748470105dee3197adb29589
